spring.application.name=user-service
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/auth}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:delej}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234567890}

spring.jpa.hibernate.ddl-auto=update