# docker-compose.yml
services:
  # ========== AUTH SERVICE ==========
  # auth-service:
  #   build: ./backend/auth-service
  #   ports:
  #     - "3001:3000"
  #   environment:
  #      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@auth-db:5432/${DB_NAME}
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./backend/auth-service
  #         target: /app
  #         ignore:
  #           - node_modules/
  #       - action: rebuild
  #         path: ./backend/auth-service/package.json
  #   depends_on:
  #     auth-db:
  #       condition: service_healthy

  # auth-db:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_DB: ${DB_NAME}
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - auth-data:/var/lib/postgresql/data
  frontend:
      build: ./frontend
      ports:
        - "3000:3000"  # или 5173 для Vite, или 3000 для CRA
      environment:
        - REACT_APP_API_URL=http://localhost:3001  # URL бэкенда
        - CHOKIDAR_USEPOLLING=true  # для hot-reload в Docker
        - WATCHPACK_POLLING=true    # для webpack 5+
      develop:
        watch:
          - action: sync
            path: ./frontend
            target: /app
            ignore:
              - node_modules/
          - action: rebuild
            path: ./frontend/package.json
      depends_on:
        - auth-service
volumes:
  auth-data:
