
-- 1. Пользователи (используем GENERATED BY DEFAULT для гибкости)
CREATE TABLE IF NOT EXISTS app_user (
    user_id        UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    username       VARCHAR(255) NOT NULL UNIQUE,
    "name"           VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL
);

CREATE TYPE friendship_status AS ENUM ('pending', 'accepted', 'declined', 'blocked');

CREATE TABLE IF NOT EXISTS friendships (
    user_id_1     UUID NOT NULL,  -- всегда меньший id
    user_id_2     UUID NOT NULL,  -- всегда больший id
    initiator_id  UUID NOT NULL,  -- кто отправил заявку
    status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at    TIMESTAMP NOT NULL DEFAULT now(),
    
    -- Составной первичный ключ
    CONSTRAINT friendships_pkey PRIMARY KEY (user_id_1, user_id_2),
    
    -- Внешние ключи (ссылаются на app_user)
    CONSTRAINT friendships_user1_fk FOREIGN KEY (user_id_1)
        REFERENCES app_user(user_id) ON DELETE CASCADE,
    CONSTRAINT friendships_user2_fk FOREIGN KEY (user_id_2)
        REFERENCES app_user(user_id) ON DELETE CASCADE,
    CONSTRAINT friendships_initiator_fk FOREIGN KEY (initiator_id)
        REFERENCES app_user(user_id) ON DELETE CASCADE,
    

)