-- Расширение для генерации UUID (если нужно, для версий <13)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Пользователи (используем GENERATED BY DEFAULT для гибкости)
CREATE TABLE IF NOT EXISTS app_user (
    user_id        UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    username       VARCHAR(255) NOT NULL UNIQUE,
    name           VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL
);

CREATE TYPE friendship_status AS ENUM ('pending', 'accepted', 'declined', 'blocked');

-- 3. Таблица друзей – составной ключ + внешние ключи + проверка порядка
CREATE TABLE IF NOT EXISTS friendship (
    user_id_1   UUID                NOT NULL,
    user_id_2   UUID                NOT NULL,
    status      friendship_status   NOT NULL DEFAULT 'pending',
    created_at  TIMESTAMP(0)        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Составной первичный ключ
    CONSTRAINT friendship_pkey PRIMARY KEY (user_id_1, user_id_2),

    -- Внешние ключи с каскадным удалением
    CONSTRAINT friendship_user1_fk FOREIGN KEY (user_id_1)
        REFERENCES app_user(user_id) ON DELETE CASCADE,
    CONSTRAINT friendship_user2_fk FOREIGN KEY (user_id_2)
        REFERENCES app_user(user_id) ON DELETE CASCADE,

    -- Гарантируем, что user_id_1 < user_id_2 (избегаем дублей типа (2,1))
    CONSTRAINT friendship_order_check CHECK (user_id_1 < user_id_2)
);

-- 4. Индексы для ускорения поиска по каждому пользователю
CREATE INDEX idx_friendship_user1 ON friendship(user_id_1);
CREATE INDEX idx_friendship_user2 ON friendship(user_id_2);
CREATE INDEX idx_friendship_status ON friendship(status);   -- полезно для выборок по статусу

-- 5. Комментарии к таблицам и колонкам (красиво для документации)
COMMENT ON TABLE  app_user        IS 'Зарегистрированные пользователи';
COMMENT ON COLUMN app_user.user_id IS 'Уникальный идентификатор (UUID v4)';
COMMENT ON COLUMN app_user.username IS 'Логин пользователя';

COMMENT ON TABLE  friendship      IS 'Связи дружбы между пользователями';
COMMENT ON COLUMN friendship.status IS 'Статус: pending, accepted, declined, blocked';
COMMENT ON COLUMN friendship.created_at IS 'Время создания запроса на дружбу';