spring:
  application:
    name: event-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/event_db}
    username: ${SPRING_DATASOURCE_USERNAME:delej}
    password: ${SPRING_DATASOURCE_PASSWORD:1234567890}
    driver-class-name: org.postgresql.Driver  # ← Добавьте это
  
  jpa:
    database: POSTGRESQL  # ← Добавьте это
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # ← Добавьте это
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # ← Добавьте это
        jdbc:
          lob:
            non_contextual_creation: true  # ← Добавьте это

server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /api

jwt:
  secret: q1JBE17iCKMS67BkgSKTAvWGNUtpMe3YE9YfmNCxuow
  expirationMs: 3600000